### ISSUE TITLE
Change CodeArea default textcolor

### ISSUE THREAD

**Issue by kanashius** [TomasMikula/RichTextFX#187]
Maybe an Issue, maybe I just do not know, how to do it.
I want to set the default text of the CodeArea. 
I changed:
.code-area{
  -fx-background-color:#222222;
}
.styled-text-area .label{
  -fx-background-color:#111111;
  -fx-text-fill:#888888;
}
.code-area .scroll-bar:horizontal ,
.code-area  .scroll-bar:vertical{
  -fx-background-color:#000000;
}
.code-area .scroll-bar:horizontal .thumb{
  -fx-background-color: linear-gradient(#040404 0%,#1d1d1d 50, #040404 0%);
}
.code-area  .scroll-bar:vertical .thumb{
  -fx-background-color: linear-gradient(to right,#040404 0%,#1d1d1d 50, #040404 0%);
}
As workaround I used all not matched characters (Syntax) as another matchgroup with the textcolor.

**Comment by TomasMikula** [comment]
The following should do:

```css
.code-area .text {
	-fx-fill: #888888;
}
```

In order to not override other styles, make the selectors for other styles more specific, i.e. `.code-area .text.keyword` instead of just `.keyword`.

**Comment by kanashius** [comment]
Thank you, that works fine :+1: 
Just did not find the .text... Tryed so much link list-view, list-cell,label,...

**Comment by dim-s** [comment]
@TomasMikula 

What about LineNumberFactory with the `.lineno` class? If I use this css selectory `.code-area .text`, it changes color for the line number labels and `.code-area .lineno` doesn't work. My css:

```css
.code-area .text {
    -fx-fill: #E0E2E4;
}
.code-area .lineno {
    -fx-text-fill: red;
    -fx-fill: red;
}
```

**Comment by TomasMikula** [comment]
Hi, can you please try using a more specific selector in order to take precedence, like

```css
.code-area .lineno .text {
    -fx-fill: red;
}
```

or a more specific selector that does not select line numbers to start with, like

```css
.code-area .text-flow .text {
    -fx-fill: #E0E2E4;
}
```

?
