### ISSUE TITLE
How to remove line highlight in StyleClassedTextArea?

### ISSUE THREAD

**Issue by euwbah** [TomasMikula/RichTextFX#262]
Currently I got this:

```
console = new StyleClassedTextArea();
        console.setEditable(false);

        console.setStyle("-fx-background-color: rgba(0, 0, 0, 1)");
```

A blue line background highlight appears (like how it does in a CodeArea). How do I remove this blue line highlight?

**Comment by JordanMartinez** [comment]
Does this relate at all to #254, which was implemented only recently?

**Comment by JordanMartinez** [comment]
Could you provide a screenshot?

**Comment by JordanMartinez** [comment]
I can't reproduce the blue background highlight about which you're talking with the code you've provided.

**Comment by euwbah** [comment]
Yes it actually does relate to #254. How do I remove that style?

**Comment by JordanMartinez** [comment]
I'm not sure why the blue line is even appearing because there are currently no style sheets being applied to `StyleClassedTextArea` that would give it that look. Are you doing something more than the above code? Because your problem shouldn't be happening in the first place.

Still, I'm guessing that the blue line only appears in the line that has the caret. Or, if it's the first or last paragraph, see the next two. If so, you'd need to write a CSS file that has something like this:
````css
// in a custom css file that you apply...

// this is for the has-caret pseudo class
.paragraph-box:has-caret {
    -fx-background-color: rgba(0, 0, 0, 1);
}

// if it's not that, then this is for the first-paragraph and last-paragraph pseudo class
.paragraph-box:first-paragraph, .paragraph-box:last-paragraph {
    -fx-background-color: rgba(0, 0, 0, 1);
}
````
and then add that to your custom CSS file to your class's stylesheets
