### ISSUE TITLE
How to change color of caret?

### ISSUE THREAD

**Issue by JavaSaBr** [TomasMikula/RichTextFX#268]
How to change color of caret? I would like change color of caret to white.

**Comment by TomasMikula** [comment]
There's no property to set that, but you should be able to set it via CSS:

```css
.styled-text-area .caret {
    -fx-stroke: white;
}
```
