### ISSUE TITLE
DropShadow on TextExt

### ISSUE THREAD

**Issue by msmithurbna** [TomasMikula/RichTextFX#326]
Hi I'm trying to set a DropShadow on text, but it doesn't seem to work.  Is this supported?

BTW I can successfully set a DropShadow on a CodeArea, but not on a TextExt.

Thanks

**Comment by TomasMikula** [comment]
This is the JavaKeywords demo with the following CSS:

```css
.keyword {
    -fx-fill: purple;
    -fx-font-weight: bold;
    -fx-effect: dropshadow(gaussian, yellow, 6, 0.5, 0, 0);
}
```

<img width="712" alt="screen shot 2016-06-12 at 1 32 43 pm" src="https://cloud.githubusercontent.com/assets/433439/15992759/2f13dc4e-30a2-11e6-9bad-7d7b178dac3c.png">

Do you mind providing more details?
