### ISSUE TITLE
Change text color of StyledClassedTextArea with css

### ISSUE THREAD

**Issue by firm1** [TomasMikula/RichTextFX#328]
Hi,

Thank a lot for your lib, but i have a new problem with RichTextFx. I use v0.6.10 of your lib.
I have a `StyleClassedTextArea` and i need to change color of text by css styling.

With this java code : 

```java
myText.getStyleClass().add("markdown-editor");
```

I tried try many things in css.

```css
.markdown-editor {
    -fx-background-color:#000;
    -fx-text-fill: #FFF;
}
```

or

```css
.markdown-editor {
    -fx-background-color:#000;
    -fx-fill: #FFF;
}
```

```css
.markdown-editor .label{
    -fx-background-color:#000;
    -fx-text-fill: #FFF;
}
```

Whatever css, my background is black, but my text stay black despite my attempts.

Do you know any solution for change text color ?

**Comment by TomasMikula** [comment]
Assuming `myText` is an instance of `StyleClassedTextArea`, you would need something like

```css
.markdown-editor .text {
    -fx-fill: #FFF;
}
```
